version: '3.4'

services:
  hello-grpc:
    image: ${DOCKER_REGISTRY-}hellogrpc
    build:
      context: .
      dockerfile: hello-grpc/Dockerfile

  hello-controller:
    image: ${DOCKER_REGISTRY-}hellocontroller
    build:
      context: .
      dockerfile: hello-controller/Dockerfile

